services:
  camunda:
    #   image: camunda/camunda-bpm-platform:${DISTRO:-latest}
      image: camunda/camunda-bpm-platform:latest
      environment:
          - DB_DRIVER=org.postgresql.Driver
          - DB_URL=jdbc:postgresql://postgres:5432/camunda
          - DB_USERNAME=camunda
          - DB_PASSWORD=camunda
          - WAIT_FOR=postgres:5432
      # Uncomment for custom application
      # volumes:
      #     - ../webapps/poedss.war:/camunda/webapps/poedss.war
      links:
          - postgres
      ports:
          - "8080:8080"
      restart: unless-stopped
      hostname: camunda.local
      networks: 
        devnet:
          aliases:
            - camunda.local

  postgres:
      image: postgres:9.6
      environment:
          - POSTGRES_USER=camunda
          - POSTGRES_PASSWORD=camunda
      networks:
        - devnet

networks:
  devnet:
    external:
      name: devnet