version: '3'

services:
  app:
    container_name: poedss_devcontainer
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks: 
      devnet:
        aliases:
          - dev.local
    hostname: dev.local

networks:
  devnet:
    external:
      name: devnet